### ISSUE TITLE
Change convert API for class

### ISSUE THREAD

**Issue by atassis** [xxczaki/cashify#3]
I suppose it is better from different perspectives to move from `instance.convert(amount, { from, to })` to `instance.convert(amount, from, to)`. First type of API declaring uses both options object and plain argument usage, in which:
1. Is inconsistent
2. Object is being created each time for options, while we can use supplied data directly.
[Inline caching](https://mathiasbynens.be/notes/shapes-ics) in v8 does better if you provide the simplest data structure in function arguments including the object structure. We can try to do the same with the `convert` and `getRate` functions as well, but here the choice to make is not so clear. 
And yes, thank you for the library!

**Comment by xxczaki** [comment]
Hi,

For now, I will stay with the options object. I do see the benefits from using plain arguments, but I want to stay consistent with the money.js library and allow for smoother migration.

I will, however convert the `getRate` function, as it should be simplified. 

Maybe in the next major release (`2.0.0`), I will move both the `convert` function and class to use plain arguments :smile:
