### ISSUE TITLE
Equivalent of money.js' basic parsing in Cashify

### ISSUE THREAD

**Issue by iamanas20** [xxczaki/cashify#8]
Hello, congratulations on this awesome library, enjoying it so far.
I have  question, is there a way I can convert without specifying the `from` property, and cashify would detect the from currency?
Like in money.js you got:
`fx("$1.99 HKD").to("EUR");`
is it possible in cashify?
Thank you!

**Comment by xxczaki** [comment]
Thanks for the suggestion! Basic parsing is available in release `2.2.0`. It uses the same code as money.js, so everything should work the same :smile:

**Comment by xxczaki** [comment]
Here are the docs: https://github.com/xxczaki/cashify#basic-parsing
