### ISSUE TITLE
Having issues using Cashify on Firefox browser

### ISSUE THREAD

**Issue by mding5692** [xxczaki/cashify#9]
Using Cashify crashes our company's web app on the Firefox browser. 
The error message on the browser console is this: `SyntaxError: invalid regexp group`.

Googling for solutions related to this issue, I found these:
https://bugzilla.mozilla.org/show_bug.cgi?id=1559253
https://stackoverflow.com/questions/55774080/firefox-gives-syntaxerror-invalid-regexp-group

I'm using Firefox v 73.0.1 which came out Feb 18th 2020 so its still a recent issue and can affect others.

Can you review and merge this fork which solves the issue:
https://github.com/SergioReis97/cashify

Much thanks!

**Comment by xxczaki** [comment]
Thanks for reporting this issue! Cashify was using named capture groups, which are not supported in Firefox. I removed them in [`2.4.1`](https://github.com/xxczaki/cashify/releases/tag/2.4.1), so everything should be working fine now.

If this problem will still occur, please reopen :smile:

**Comment by mding5692** [comment]
Ok much thanks :)
